### ISSUE TITLE
WARN Failed to read configuration file: The system cannot find the path specified. (os error 3)

### ISSUE THREAD

**Issue by abdmankhan** [H-M-H/Weylus#102]
how to use this software. and what is this address of your computer???

**Comment by abdmankhan** [comment]
please tell in simple words for windows user. This is the main screen of wylus. i tried entering http://0.0.0.0:1701 for nothing happened in mozilla.

![Screenshot_1](https://user-images.githubusercontent.com/76775878/126888316-7e58869c-b1f5-43b5-a97e-eef6ff7f70c7.png)

**Comment by H-M-H** [comment]
0.0.0.0 is a special address that tells Weylus to use all available IPv4 addresses of your computer but can not be used to to connect another device to your computer. You need the IPv4 address of your computer for that; you can obtain it for example by typing `ipconfig` and then enter into the cmd.exe. You should get something like 192.168.1.42. And this is the address you need to connect your tablet, type this into your browser: `http://192.168.1.42:1701` with your IPv4 address instead of the example I gave here.

**Comment by H-M-H** [comment]
If you still have trouble getting Weylus to work comment again, closing for now.
