### ISSUE TITLE
Specify 'keyboard support' in README

### ISSUE THREAD

**Issue by TrevCan** [H-M-H/Weylus#107]
Hey, i was kind of disappointed when I tried to launch the native iOS keyboard from my iPad to control my computer since I didn't know how to! I just found out after reading around in issue #69 that it will only work with a physical keyboard (such as one connected to bluetooth or connected through usb (?) ) and tried it and work! I'd only suggest adding it to the README for support and clarification. 

Ofc, I'd be interested maybe if we could implement some gestures (or simply a button in the config ui) into the web app that allows you to maybe open the native keybard (in case of android/ios) for better ease of use. 

By the way, impressive app! I was really looking for this and just found about today that software this good exists!

**Comment by H-M-H** [comment]
That is  good point, I will add some info to the Readme!

> Ofc, I'd be interested maybe if we could implement some gestures (or simply a button in the config ui) into the web app that allows you to maybe open the native keybard (in case of android/ios) for better ease of use.

This is actually more difficult than you'd think at first. The big advantage of physical keyboards is that those send keycodes for each key you press and these codes can be used to simulate the corresponding keys on the desktop. Native/Onscreen keyboards do not work like that, their focus is text composition and most of them do not send keycodes (GBoard does not, https://github.com/klausw/hackerskeyboard does) but rather just the completed text (this is somewhat simplified though). This means I'd need to translate any Unicode characters (because that's all the information I get about what's being typed) back into keycodes, which basically only works for ASCII and would result in pretty poor user experience. And that's why this probably won't ever be implemented.
For more juicy details and a heated discussion, take some popcorn and read: https://bugs.chromium.org/p/chromium/issues/detail?id=118639

> By the way, impressive app! I was really looking for this and just found about today that software this good exists!

Thank you very much, always happy to hear this :D!

**Comment by TrevCan** [comment]
> For more juicy details and a heated discussion, grab some popcorn and read: https://bugs.chromium.org/p/chromium/issues/detail?id=118639

Lol,

Thanks for your response.

I’ll close the issue now.
