### ISSUE TITLE
[Feature] Allow to run custom scripts from UI interface

### ISSUE THREAD

**Issue by vishal733** [H-M-H/Weylus#114]
More explanation of the use-case:

- When I am using the iPad, want to enable the second monitor. When not using iPad, want to disable the second monitor.
- I could create two scripts, one which enables the second monitor, and one which disables it on the PC.
- These scripts/any other useful scripts could triggered directly from the webpage being accessed on iPad.

Of course this is just a fancy wish-list.
Feel free to close this issue if it's something beyond the scope of what you'd like to support.

**Comment by H-M-H** [comment]
This sounds (at least somewhat) useful. I do not like the idea of having Weylus directly call some external program though. With the current release of Weylus the things you requested are already almost possible to do by parsing log messages. That's why I improved logging a little and added structured logging, optionally Weylus can now output json messages instead of plain text for logging. Additionally I added some more messages so clients connecting and disconnecting can be properly detected.

The following is a very basic example in python, that outlines what you can do with the latest master (builds can be found here: https://github.com/H-M-H/Weylus/actions/runs/1298627342#artifacts):
```python
#!/usr/bin/env python

import sys
import json

for line in sys.stdin:
    d = json.loads(line)
    if d["target"] == "weylus::websocket":
        msg = d["fields"]["message"]
        if msg == "Got message from client.":
            client_msg = json.loads(d["fields"]["client_message"])
            print(client_msg)
            # do something with it
        if msg == "Client connected.":
            addr = d["fields"]["address"]
            print(f"Client connected: {addr}")
        if msg == "Client disconnected.":
            addr = d["fields"]["address"]
            print(f"Client disconnected: {addr}")
```
Save it as `test.py` and run `WEYLUS_LOG_JSON="1" WEYLUS_LOG_LEVEL="TRACE" ./weylus | ./test.py`.

**Comment by vishal733** [comment]
Sounds good. This should be usable for me. 
I will close this issue.
And as an appreciation for your effort, just did a 1-time sponser. Thanks!

**Comment by vishal733** [comment]
Not sure if the payment actually went through. I will retry again. 
And apoloigies for mentioning irrelevant stuff on an issue.

**Comment by H-M-H** [comment]
Awesome, thank you very much!
