### ISSUE TITLE
Error: This browser doesn't support MSE - iPadOS 15

### ISSUE THREAD

**Issue by tyleraharrison** [H-M-H/Weylus#118]
As suggested in the README:

> You may want to add a bookmark to your home screen on your tablet as this enables running Weylus in full screen mode (on iOS/iPadOS this needs to be done with Safari). If you are not on iOS/iPadOS there is a button to toggle full screen mode.

Unfortunately, upon doing that, we get the error: 
`This browser doesn't support MSE required to playback video stream, try upgrading! `

Oddly enough this doesn't happen in Safari itself, only when bookmarking to the home page from Safari and launching it

**Comment by H-M-H** [comment]
Any updates on this, have you found a solution?

**Comment by an4s911** [comment]
I have the same problem on iOS. Why is this issue closed? Anyone found any solution?

**Comment by an4s911** [comment]
I think [this similar thread on another GitHub repo](https://github.com/video-dev/hls.js/issues/2267) might help. One of the comments in that thread mentions:

> > do you guys know when apple is planning to support Media Source extensions for IOS Safari and Chrome on Mobile. Have a project that's dependent on using this wonderful API.
>
> you can use canvas + websockets, this is supported on iOS
[link to comment](https://github.com/video-dev/hls.js/issues/2267#issuecomment-548865653)

**Comment by H-M-H** [comment]
Hello @an4s911 I am afraid but there is not much I can do about Weylus for iOS (as opposed to iPadOS). Apple decided not to support MSE on iOS and thus video streaming won't work on iPhones. The two possible solutions I see are: Apple adding support for MSE on iOS or me implementing a canvas renderer for Weylus. The problem about this is, that I'd need to decode the video stream using JavaScript, which is not very desirable, especially regarding latency. That's why iOS is currently unsupported and this issue closed.

If anyone wants to experiment with this anyways and if this is actually a viable solution w.r.t. to latency I am open to pull requests.

**Comment by Papermanzero** [comment]
is it possible to add IOS support?

**Comment by H-M-H** [comment]
@Papermanzero sadly probably not as long as Apple doesn't add support for MSE on iOS.

**Comment by Software27425** [comment]
@H-M-H It looks like it's possible now with MMS (backwards compatible with MSE) as of the latest iOS version? Think support can be added to Weylus now?

https://bitmovin.com/managed-media-source/#migration-from-mse-to-mms-ed4921d7-725c-4010-b3d0-d32af2f44964

**Comment by Papermanzero** [comment]
That’s an awesome news. Weylus is by far the best open source multi screen app.
