### ISSUE TITLE
não consigo conctar no celular

### ISSUE THREAD

**Issue by deiandrill** [H-M-H/Weylus#125]
Olá eu conecto mno computador e fica tudo ok, mas na hora de conectar no celular ele fica demorando e da erro
Ja tentei em 2 celulares.
Alguem sabe como resolver.

**Comment by H-M-H** [comment]
Em primeiro lugar, não falo português. Estou usando o Google tradutor. Provavelmente seu celular está na rede errada. Tem que haver uma conexão direta entre o telefone celular e o computador. Não funcionará de outra forma. Certifique-se de que o computador e o telefone celular estejam conectados à mesma rede, por exemplo, o mesmo WIFI. Alternativamente, você pode tentar criar um ponto de acesso com seu telefone celular e conectar seu computador a ele. Mas só posso adivinhar o que está errado. Para melhor te ajudar, preciso de mais detalhes. Qual é o seu sistema operacional, Linux, Windows ou macOS? Como o seu computador e telefone celular estão conectados à rede? É o seu celular Android ou iOS.

---

First of all, I do not speak Portuguese. So I am using Google translate. Probably your cell phone is on the wrong network. There has to be a direct connection between cell phone and computer. It won't work otherwise. Make sure both computer and cell phone are connected to the same network, for example the same WIFI. Alternatively you can try to create a hotspot with your cell phone and connect your computer to that. But I can only guess what's wrong. To better help you, I need more details. What's your OS, Linux, Windows or macOS? How is your computer and cell phone connected to the network? Is your cell phone Android or iOS.
