### ISSUE TITLE
Can Weylus works like Pen Tablet instead of normal Tablet?

### ISSUE THREAD

**Issue by alvindimas05** [H-M-H/Weylus#233]
So when I'm drawing I want the input not to change position at first, since I'm focusing to my laptop instead of my phone. It's like you are playing OSU, etc

**Comment by tutacat** [comment]
Pen tablet also uses absolute positioning. Just keep your input in the same place. Don't know what you mean by a "normal tablet", since that is an ambiguous word.

If you mean you want to show the cursor, it may not work, because it emulates a touchscreen. Some programs have an option to show a cursor for the touchscreen also, but most operating systems don't have an option to do that globally.

**Comment by H-M-H** [comment]
I think what you want has been requested in #98 already.
