### ISSUE TITLE
Using the nullish coalescing operator (??) in javascript breaks usability for some mobile devices

### ISSUE THREAD

**Issue by doeblerh** [H-M-H/Weylus#32]
In lib.ts (loaded in browser as lib.js) line 106, the nullish coalescing operator (??) is used, causing a syntax error in some mobile web browsers.

See [Nullish_Coalescing_Operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_Coalescing_Operator) -> Browser compatibility

**Comment by H-M-H** [comment]
According to above reference the following mobile browsers do not support `??` (yet):
- Firefox for Android
- Opera for Android
- Samsung Internet

The only problem I see is Firefox. However, there is Firefox Beta and Firefox Nightly, which work fine. Additionally Firefox for Android does not yet support doing anything with a [SourceBuffer](https://developer.mozilla.org/en-US/docs/Web/API/SourceBuffer) (required for video playing) and thus replacing `??` is not going to make Weylus work there.

If you have problems with another browser or you think replacing `??` can make Weylus work in another browser, please tell me, otherwise this issue can probably be closed.

**Comment by doeblerh** [comment]
Ok, I didn't notice that even fixing this wouldn't help to get it working in FF for Android. You are making a very good point here.

I therefore agree that since fixing this issue would not make any difference, it can be closed for now.

**Comment by H-M-H** [comment]
Alright, thanks for the report nonetheless!
