### ISSUE TITLE
Left mouse button always pressed?

### ISSUE THREAD

**Issue by reparator** [H-M-H/Weylus#60]
Works fine so far for cloning the screen!
Hardware: Samsung Galaxy Tab S2 w. Android 7 and Firefox 84.1.4. 
(the original chrome does not clone the desktop screen)
PC: Ubuntu 18.04 LTS
One issue I have:
When I move the finger on my tablet it simulates always that a mouse button is pressed. 
It is the same behavior as dragging the mouse with the left button pressed. 
Any idea how to avoid that behavior?
And: How do I simulate a select-button (left mouse click), a right-mouse-click or a double-click? 
Regards Stefan

**Comment by H-M-H** [comment]
Hello Stefan,

this behavior is intentional. Basically Weylus uses the touch screen API of the kernel to simulate events, so touching = clicking most of the time. But you will notice that some applications like firefox properly handle touch events and in firefox you can scroll like you would on a smartphone. In this context left and right mouse clicks don't make much sense and I am not sure how to integrate them. The only thing I might do in the future is to add a touch pad mode and let Weylus simulate a touch pad.

If you want to do some experiments yourself:

Event that the browser sends:
https://github.com/H-M-H/Weylus/blob/f6e9dd8a20c0fdb81bda1fe9d84d48f51bdc8f71/src/protocol.rs#L73-L93
Code that handles the event:
https://github.com/H-M-H/Weylus/blob/f6e9dd8a20c0fdb81bda1fe9d84d48f51bdc8f71/src/input/uinput_device.rs#L208
Some resources on how to simulate input events:
https://github.com/H-M-H/Weylus/blob/f6e9dd8a20c0fdb81bda1fe9d84d48f51bdc8f71/lib/linux/uinput_info.md

But I am always open to suggestions.

**Comment by reparator** [comment]
Hello H-M-H,
thanks for the quick answer!
> this behavior is intentional. 
Ok, I see. I tried with a fresh firefox on my mobil and indeed it works with that as expected. I will try on my tablet soon as well. 
My intention to use the program is to draw onto a canvas during video conferences. Writing with the tools the conference systems supplies is painfull and drawing and writing with the mouse just as well. I will tryout Weylus tomorrow with that conference system. 

By the way: Two short tips consecutively could be interpreted as double-click.
