### ISSUE TITLE
Missing libffi6 on Ubuntu 20.04

### ISSUE THREAD

**Issue by Budaquepariu** [H-M-H/Weylus#81]
Ubuntu 20.04 comes with libffi7.
Gladly there is a .deb package to manually install libffi6. The package is available on online mirror repos.

**Comment by H-M-H** [comment]
Can anyone confirm this? From what I can tell neither `libffi6` nor `libffi7` are mentioned in the direct dependencies from the generated `.deb`. And `ldd weylus` doesn't show `libffi*` either. How exactly did you get this error message? Did `dpkg` print it?

**Comment by xgrg** [comment]
> Can anyone confirm this?

Having the same error here! (Ubuntu 20.04)

![image](https://user-images.githubusercontent.com/606861/114776960-6074cf80-9d73-11eb-9e73-00e97e64a8f5.png)

**Comment by H-M-H** [comment]
Alright, thanks for verifying this! I have figured out what the problem is: Basically the tool I use to create the `.deb` places some unnecessary constraints on what packages need to be installed, I have opened an issue there: https://github.com/mmstick/cargo-deb/issues/170

In the mean time, can you guys please check if the binary from the `linux.zip` works fine?

**Comment by xgrg** [comment]
Yes, the binary works beautifully!
(and so does the fix for missed strokes by removing the `scribble` option)
Thanks a lot!

**Comment by H-M-H** [comment]
Excellent! The `.deb` should be fix now as well.
